use petunia_config::keybinds::winit_keys::KeyCode;

pub(crate) fn key_code_from_slint(text: &str) -> Option<KeyCode> {
    let normalized = text.trim();
    if normalized.len() == 1 {
        let character = normalized.chars().next()?.to_ascii_uppercase();
        return match character {
            'A' => Some(KeyCode::KeyA),
            'B' => Some(KeyCode::KeyB),
            'C' => Some(KeyCode::KeyC),
            'D' => Some(KeyCode::KeyD),
            'E' => Some(KeyCode::KeyE),
            'F' => Some(KeyCode::KeyF),
            'G' => Some(KeyCode::KeyG),
            'H' => Some(KeyCode::KeyH),
            'I' => Some(KeyCode::KeyI),
            'J' => Some(KeyCode::KeyJ),
            'K' => Some(KeyCode::KeyK),
            'L' => Some(KeyCode::KeyL),
            'M' => Some(KeyCode::KeyM),
            'N' => Some(KeyCode::KeyN),
            'O' => Some(KeyCode::KeyO),
            'P' => Some(KeyCode::KeyP),
            'Q' => Some(KeyCode::KeyQ),
            'R' => Some(KeyCode::KeyR),
            'S' => Some(KeyCode::KeyS),
            'T' => Some(KeyCode::KeyT),
            'U' => Some(KeyCode::KeyU),
            'V' => Some(KeyCode::KeyV),
            'W' => Some(KeyCode::KeyW),
            'X' => Some(KeyCode::KeyX),
            'Y' => Some(KeyCode::KeyY),
            'Z' => Some(KeyCode::KeyZ),
            '0' => Some(KeyCode::Digit0),
            '1' => Some(KeyCode::Digit1),
            '2' => Some(KeyCode::Digit2),
            '3' => Some(KeyCode::Digit3),
            '4' => Some(KeyCode::Digit4),
            '5' => Some(KeyCode::Digit5),
            '6' => Some(KeyCode::Digit6),
            '7' => Some(KeyCode::Digit7),
            '8' => Some(KeyCode::Digit8),
            '9' => Some(KeyCode::Digit9),
            '[' => Some(KeyCode::BracketLeft),
            ']' => Some(KeyCode::BracketRight),
            _ => None,
        };
    }
    match normalized {
        "Delete" => Some(KeyCode::Delete),
        "Backspace" => Some(KeyCode::Backspace),
        "Home" => Some(KeyCode::Home),
        "Enter" => Some(KeyCode::Enter),
        "Escape" => Some(KeyCode::Escape),
        "F1" => Some(KeyCode::F1),
        "F2" => Some(KeyCode::F2),
        "F3" => Some(KeyCode::F3),
        "F4" => Some(KeyCode::F4),
        "F5" => Some(KeyCode::F5),
        "F6" => Some(KeyCode::F6),
        "F7" => Some(KeyCode::F7),
        "F8" => Some(KeyCode::F8),
        "F9" => Some(KeyCode::F9),
        "F10" => Some(KeyCode::F10),
        "F11" => Some(KeyCode::F11),
        "F12" => Some(KeyCode::F12),
        _ => None,
    }
}
