[package]
name = "petunia_ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "C-ABI / FFI Dynamic and Static Library for Petunia3D External Frontends"

[lib]
name = "petunia_ffi"
crate-type = ["cdylib", "rlib"]

[dependencies]
petunia_core = { workspace = true }
petunia_mesh = { workspace = true }
petunia_project = { workspace = true }
uuid = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
