[package]
name = "petunia_project"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
petunia_mesh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
postcard = { version = "1", features = ["alloc"] }
thiserror = { workspace = true }
bytemuck = "1"
glam = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }
tempfile = { workspace = true }
tobj = { workspace = true }
gltf-json = { workspace = true }
gltf = "1"
zip = { workspace = true }

[dev-dependencies]
gltf = "1"
serde_json = "1"
assert_fs = { workspace = true }
insta = { workspace = true }
